name: 'Build'

on:
  push:
    branches:
      'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Test Coffee Machine
        run: mvn verify
        working-directory: coffee-machine
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/target/*-reports/TEST*.xml'
  ui-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        working-directory: coffee-machine-ui
      - name: Build Coffee Machine UI
        run: npm run build
        working-directory: coffee-machine-ui
      - uses: actions/upload-artifact@v3
        with:
          name: ui
          path: coffee-machine-ui/build/
          if-no-files-found: error
  native-build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17
    needs: [ test, ui-build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ui
          path: coffee-machine/src/main/resources/META-INF/resources/
      - name: Build Coffee Machine
        run: ./mvnw package -Pnative
        working-directory: coffee-machine
      - uses: actions/upload-artifact@v3
        with:
          name: native-images
          path: coffee-machine/target/*-runner
          if-no-files-found: error
  docker-build:
    runs-on: ubuntu-latest
    needs: [ native-build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: native-images
          path: coffee-machine/target
      - uses: actions/download-artifact@v3
        with:
          name: ui
          path: coffee-machine/src/main/resources/META-INF/resources/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/robkenis/chaos-coffee/coffee-machine
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Build Coffee Machine
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./coffee-machine/Dockerfile
          context: ./coffee-machine/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/robkenis/chaos-coffee/docs
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Build Documentation
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./docs/Dockerfile
          context: ./docs/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}