name: 'Build'

on:
  push:
    branches:
      'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Test Coffee Machine
        run: mvn verify
        working-directory: coffee-machine
  native-build:
    runs-on: ubuntu-latest
    needs: [ verify ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
      - name: Build Coffee Machine
        run: mvn package -Pnative
        working-directory: coffee-machine
      - uses: actions/upload-artifact@v3
        with:
          name: native-images
          path: coffee-machine*/target/*-runner
          if-no-files-found: error
  docker-build:
    runs-on: ubuntu-latest
    needs: [ native-build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: native-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/robkenis/chaos-coffee/coffee-machine
      - name: Build Coffee Machine
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./coffee-machine/Dockerfile
          context: ./coffee-machine/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

